import mmh3

s = "ACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAGACGTGCAG"
k = 21

for i in range(len(s) - k + 1):
    print(mmh3.hash64(s[i:i+k], signed=False))